import boto3

def lambda_handler(event, context):
    # Retrieve the S3 bucket and object information from the event
    bucket_name = event['Records'][0]['s3']['bucket']['name']
    object_key = event['Records'][0]['s3']['object']['key']
    print(bucket_name)
    print(object_key)
    
    # Create an S3 client
    s3_client = boto3.client('s3')
    
    # Retrieve the uploaded file from S3
    response = s3_client.get_object(Bucket=bucket_name, Key=object_key)
    file_content = response['Body'].read().decode('utf-8')
    
    # Perform some processing or business logic with the file content
    # For example, you could process the data, extract information, or store it in a database.
    # Here, we'll simply print the file content for demonstration purposes.
    print(file_content)
    
    # Return a response if needed
    return {
        'statusCode': 200,
        'body': 'File uploaded and processed successfully.'
    }





S3 Event JSON description
The given code represents a JSON structure that provides information about an event that triggered an AWS Lambda function. Here's a breakdown of the different components within the JSON structure:

Records: This is an array that contains the details of the triggered event. In this case, there is one event in the array.

eventVersion: Specifies the version of the event structure.

eventSource: Indicates the source of the event, which is AWS S3 in this example.

awsRegion: Specifies the AWS region where the event occurred, such as "us-east-1".

eventTime: Represents the timestamp of the event in UTC format.

eventName: Describes the specific event type that occurred. In this case, it is "ObjectCreated:Put", indicating that an object was created by a PUT request.

userIdentity: Provides information about the identity associated with the event.

requestParameters: Contains details about the request parameters, such as the source IP address.

responseElements: Includes elements related to the response generated by the event, such as the request ID and Amazon S3 ID.

s3: Contains information specific to the S3 bucket and object related to the event.

s3SchemaVersion: Indicates the version of the S3 event structure.

configurationId: Specifies the configuration ID associated with the S3 bucket.

bucket: Contains details about the S3 bucket.

name: Represents the name of the bucket, such as "example-bucket".

ownerIdentity: Provides information about the owner of the bucket.

arn: Specifies the Amazon Resource Name (ARN) of the bucket.

object: Contains details about the object within the S3 bucket.

key: Represents the object key, such as "test%2Fkey".

size: Indicates the size of the object in bytes.

eTag: Specifies the entity tag (ETag) of the object.

sequencer: Represents a unique identifier for the event sequence.

Overall, this JSON structure provides comprehensive information about an S3 event, including details about the bucket, object, event type, and other related metadata. This information can be used by the Lambda function to perform specific actions or business logic based on the event's characteristics.
